#!/usr/bin/ruby

require 'rubygems'
require 'bundler/setup'
require 'edn'

require 'optparse'
require 'net/http'
require 'digest'

require_relative 'marlin'

def verify_integrity(marlin)
  marlin.all().map { |entry|
    path = File.join(marlin.config[:root], *(entry.chars.take(3)), entry)
    if !File.exists?(path)
      warn "#{$0}: \"#{entry}\" does not exist at \"#{path}\""
      next true
    end

    if !File.readable?(path)
      warn "#{$0}: \"#{entry}\" cannot be read at \"#{path}\""
      next true
    end
    
    info = marlin.all(URI.encode(entry))
    size = File.size(path)
    if size != info[:size]
      warn "#{$0}: expected size of \"#{entry}\" (#{info[:size]})"\
           " does not match actual size of \"#{path}\" (#{size})"
      next true
    end

    digest = Digest::SHA1.file(path).hexdigest
    if digest != info[:hash]
      warn "#{$0}: expected hash of \"#{entry}\" (\"#{info[:hash]}\")"\
           " does not match actual hash of \"#{path}\" (#{digest})"
      next true
    end

    false
  }

end

options = {}
OptionParser.new do |o|
  o.banner += ' [config1 config2 ...]'

  o.on('-e', '--endpoint ADDRESS', 'specify the marlin HTTP endpoint') do |a|
    uri = URI(a)
    if uri.scheme.nil? || !["HTTP", "HTTPS"].include?(uri.scheme.upcase)
      abort "#{$0}: endpoint must be http or https"
    end

    options[:endpoint] = uri
  end

  o.on('-r', '--root DIRECTORY', "specify marlin's root directory") do |d|
    if !File.directory?(d)
      abort "#{$0}: marlin's root directory must actually be a directory"
    end

    options[:root] = d
  end

  o.on('-h', '--help', 'print this usage message and exit') do
    puts o
    exit
  end

  o.parse!

  # if one is set, the other must be as well
  either = !(options[:endpoint].nil? && options[:root].nil?)
  both = !(options[:endpoint].nil? || options[:root].nil?)
  if either && !both
    abort "#{$0}: must specify endpoint and root directory" 
  end

  if !either && ARGV.empty?
    puts o
    exit
  end
end

if !options.empty?
  endpoint = options[:endpoint]
  config = {
    :rest => {
      :host => endpoint.hostname,
      :port => endpoint.port
    },

    :root => options[:root]
  }

  verify_integrity(Marlin.new(config))
end

error_occurred =
  ARGV
    .map { |config|
      if !(File.file?(config) && File.readable?(config))
        abort "#{$0}: cannot open file \"#{config}\""
        next true
      end

      verify_integrity(Marlin.new(EDN.read(File.open(config, 'rb').read))).any?
    }
    .any?

exit !error_occurred
